server:
  port: 7002

eureka:
  instance:
    hostname: eureka7002.com #eureka服务端的实例名称
  client:
    register-with-eureka: false #false表示不向服务中心注册自己
    fetch-registry: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/ #http://${eureka.instance.hostname}:${server.port}/eureka/

